#pragma once

#define KEYBOARD_MAKE_AN_APPOINTMENT	u8"📝Запись на прием"
#define KEYBOARD_ACCOUNT		u8"🗓Личный кабинет"
#define KEYBOARD_SESSIONS		u8"📋Мои записи"

#define KEYBOARD_ACCOUNT_EDIT	u8"✏️Изменить данные"
#define KEYBOARD_ACCOUNT_BACK	u8"◀️Назад"

#define INLINE_KEYBOARD_REGISTRATION u8"Зарегистрироваться"

#define INLINE_KEYBOARD_CHOIСE u8"Выбрать" 

#define INLINE_KEYBOARD_ACCOUNT_EDIT_FIRSTNAME u8"Имя"
#define INLINE_KEYBOARD_ACCOUNT_EDIT_LASTNAME u8"Фамилия"
#define INLINE_KEYBOARD_ACCOUNT_EDIT_MIDDLENAME u8"Отчество"
#define INLINE_KEYBOARD_ACCOUNT_EDIT_AGE u8"Возраст"
#define INLINE_KEYBOARD_ACCOUNT_EDIT_GENDER u8"Пол"

#define INLINE_KEYBOARD_SPEC_THERAPIST u8"Терапевт"
#define INLINE_KEYBOARD_SPEC_PEDIATRICIAN u8"Педиатр"
#define INLINE_KEYBOARD_SPEC_SURGEON u8"Хирург"
#define INLINE_KEYBOARD_SPEC_CARDIOLOGIST u8"Кардиолог"
#define INLINE_KEYBOARD_SPEC_NEUROLOGIST u8"Невролог"
#define INLINE_KEYBOARD_SPEC_GASTROENTEROLOGIST u8"Гастроэнтеролог"
#define INLINE_KEYBOARD_SPEC_DERMATOLOGIST u8"Дерматолог"
#define INLINE_KEYBOARD_SPEC_UROLOGIST u8"Уролог"